name: "Build & Release"

on:
  push:
    branches:
      - main
      - master

env:
  JAVA_VERSION: "17.0.11"
  XCODE_VERSION: "15.0.1"
  FLUTTER_VERSION: "3.22.2"
  FLUTTER_CHANNEL: "stable"
  PACKAGE_NAME: "com.robertkawaev.flutter_template"
  PROPERTIES_PATH: "./android/key.properties"
  KEY_PATH: "./android/app/key.jks"

jobs:
  setup:
    name: Setup
    runs-on: macos-14
    steps:
      # ? Подготовка репозитория
      - name: Checkout
        uses: actions/checkout@v4

      # ? Установка JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # ? Кэширование Flutter SDK (Повторное использование кэша)
      - name: Cache Flutter SDK
        id: cache
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      # ? Установка Flutter (если не из кэша)
      - name: Install Flutter
        if: steps.cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # ? Установка зависимостей Flutter
      - name: Flutter Pub Get
        run: flutter pub get

      # ? Установка нужной версии Xcode
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      # ? Установка версии сборки
      - name: Set up Bundle
        id: version_setup
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: \([0-9.]*\)+[0-9]*/\1/')
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          NEW_VERSION="${VERSION}+${BUILD_NUMBER}"
          sed -i '' "s/version: .*/version: ${NEW_VERSION}/" pubspec.yaml
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

  android:
    name: Android
    needs: [setup]
    runs-on: macos-14
    steps:
      # ? Подготовка репозитория
      - name: Checkout
        uses: actions/checkout@v3

      # ? Кэширование Flutter SDK (Повторное использование кэша)
      - name: Cache Flutter SDK
        id: cache
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      # ? Установка Flutter (если не из кэша)
      - name: Install Flutter
        if: steps.cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # ? Создание key.properties
      - name: Create key.properties
        run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{ env.PROPERTIES_PATH }}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{ env.PROPERTIES_PATH }}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{ env.PROPERTIES_PATH }}
      
      # ? Создание key.jks
      - name: Create key.jks
        run: echo "${{ secrets.KEY_STORE }}" | base64 --decode > ${{ env.KEY_PATH }}

      # ? Сборка проекта для Android
      - name: Build Android
        run: |
          flutter build apk --no-shrink
          flutter build appbundle

  ios:
    name: iOS
    needs: [setup]
    runs-on: macos-14
    steps:
      # ? Подготовка репозитория
      - name: Checkout
        uses: actions/checkout@v3

      # ? Кэширование Flutter SDK (Повторное использование кэша)
      - name: Cache Flutter SDK
        id: cache
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      # ? Установка Flutter (если не из кэша)
      - name: Install Flutter
        if: steps.cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # ? Сборка проекта для iOS
      - name: Build iOS
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

  release:
    name: Release
    needs: [android, ios]
    runs-on: macos-14
    steps:
      # ? Загрузка изменений в GitHub Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios/iphoneos/app.ipa"
          tag: v${{ env.NEW_VERSION }}
          token: ${{ secrets.TOKEN }}
