name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

env:
  JAVA_VERSION: "17.0.11"
  XCODE_VERSION: "15.0.1"
  FLUTTER_VERSION: "3.22.2"
  FLUTTER_CHANNEL: "stable"
  PROPERTIES_PATH: "./android/key.properties"
  KEY_PATH: "./android/app/key.jks"

jobs:
  build:
    name: Build & Release
    runs-on: macos-14
    steps:
      # ? Подготовка репозитория
      - name: Checkout
        uses: actions/checkout@v3

      # ? Установка JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{env.JAVA_VERSION}}

      # ? Установка Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}

      # ? Установка зависимостей Flutter
      - name: Flutter Pub Get
        run: |
          flutter clean
          flutter pub get

      # ? Установка версии сборки
      - name: Set up Bundle
        id: version_setup # Delete this ID if you don't need it
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: \([0-9.]*\)+[0-9]*/\1/')
          BUILD_NUMBER=${{ github.run_number }}
          NEW_VERSION="${VERSION}+${BUILD_NUMBER}"
          sed -i '' "s/version: .*/version: ${NEW_VERSION}/" pubspec.yaml
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      # ? Подпись проекта Android
      - name: Sign Android
        run: |
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > ${{env.KEY_PATH}}

      # ? Сборка проекта для Android
      - name: Build Android
        run: |
          flutter build apk --no-shrink
          flutter build appbundle

      # ? Установка нужной версии Xcode
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{env.XCODE_VERSION}}

      # ? Сборка проекта для iOS
      - name: Build iOS
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # ? Загрузка изменений в GitHub Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/app/outputs/bundle/release/*,build/ios/iphoneos/app.ipa"
          tag: v${{ env.NEW_VERSION }}
          token: ${{ secrets.TOKEN }}
